site_name: ludics

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Tutorials:
      - Analyse a Public Goods Game: tutorial/basics.md
  - How-To Guides:
      - Install: how-to/install.md
      - Choose a fitness function: how-to/choose_fitness_function.md
      - Define a fitness function: how-to/define_fitness_function.md
      - Choose an evolutionary dynamic: how-to/population_dynamic.md
      - Assemble the underlying Markov chain: how-to/transition_matrix.md
      - Compute absorption probabilities for absorbing processes: how-to/absorption_matrix.md
      - Compute the stationary distribution of ergodic processes: how-to/steady_state.md
      - Increase the precision of the approximate stationary distribution: how-to/steady_state_precision.md
      - Simulate dynamics for large populations: how-to/simulate_markov_chain.md
      - Compare evolutionary dynamics on a Public Goods Game: how-to/compare_dynamics.md
      - Model heterogeneous contributions for the Public Goods Game: how-to/heterogeneous_pgg.md
      - Use symbolic payoffs for a 2-player game: how-to/symbolic_fitness.md
      - Build a hybrid population dynamic: how-to/hybrid_population_dynamic.md
  - Reference:
      - List of functionality: reference/functionality.md
      - Bibliography: reference/bibliography.md
  - Explanation:
      - How states are represented: explanation/state_representation.md
      - Evolutionary games and Markov chains: explanation/markov_chain.md
      - Population dynamics: explanation/population_dynamics.md
      - Public Goods Games: explanation/public_goods_game.md
